### ISSUE TITLE
covid_out files in output directory?

### ISSUE THREAD

**Issue by arindamsaha1507** [djgroen/facs#23]
https://github.com/djgroen/facs/blob/c9a09b271f3e3e397f8c76e5afc0fe94b3f345c0/facs/base/facs.py#L23

The above-mentioned line results in the covid_out files to be written in the current directory. Would it not be better if they are written in the results directory?

**Comment by djgroen** [comment]
Hi Arindam,

Actually not, because changing this would break the curation compatibility with FabCovid19, where the current directory is always a results directory.
