### ISSUE TITLE
Unable to plot location_plot while using FabSim

### ISSUE THREAD

**Issue by arindamsaha1507** [djgroen/facs#24]
Hi Derek,

Here is the output that I get.

fabsim localhost facs_locationplot:klaipeda_localhost_1                                                                                                                                 
[loading plugin] FabDummy ...
[loading plugin] FabCovid19 ...
Error: failed to import settings module ((<class 'SyntaxError'>, SyntaxError('invalid syntax', ('/home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/plugins/FabCovid19/VVP/facs_VVP_ensemble_validation.py', 143, 22, '                     facs_vvp_sif,\n')), <traceback object at 0x7f59956ff0c0>))
The FabCovid19 ensemble VVP functionalities are not imported as a result.
[Executing task] facs_locationplot
calling task facs_locationplot from plugin FabCovid19
╭───── New/Updated environment variables from FabCovid19 plugin ─────╮
│ env :                                                              │
│   --- facs_location : /home/arindam/Dropbox/Brunel/FACS/facs/facs/ │
│   +++ facs_location : /home/arindam/Dropbox/Brunel/FACS/facs       │
│ env :                                                              │
│   +++ facs_args is a new added key                                 │
│ env :                                                              │
│   +++ facs_validation is a new added key                           │
╰────────────────────────────────────────────────────────────────────╯
calling task locate_results_dir from plugin FabCovid19
╭─ New/Updated environment variables from FabCovid19 plugin ─╮
│                                                            │
╰────────────────────────────────────────────────────────────╯
/home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/results/klaipeda_localhost_1 ['RUNS'] ['klaipeda-extend-lockdown-1.html']
/home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/results/klaipeda_localhost_1/RUNS ['extend-lockdown-1-0.475_1', 'extend-lockdown-1-0.475_2', 'extend-lockdown-1-0.475_4', 'extend-lockdown-1-0.475_3', 'extend-lockdown-1-0.475_5'] []
/home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/results/klaipeda_localhost_1/RUNS/extend-lockdown-1-0.475_1 ['covid_data'] ['covid_out_deaths_0.csv', 'env.log', 'covid_out_infections_0.csv', 'covid_out_recoveries_0.csv', 'out.csv', 'offices.csv', 'simsetting.csv', 'env.yml', 'covid_out_hospitalisations_0.csv', 'klaipeda_localhost_1_extend-lockdown-1-0.475_1.sh']
file found at: /home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/results/klaipeda_localhost_1/RUNS/extend-lockdown-1-0.475_1/covid_out_infections_0.csv
/home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/fabsim/base/decorators.py:127: DtypeWarning: Columns (0,1,2) have mixed types.Specify dtype option on import or set low_memory=False.
  return func(*args, **kwargs)
/home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/results/klaipeda_localhost_1/RUNS/extend-lockdown-1-0.475_1/covid_data [] ['needs.csv', 'measures_uk.yml', 'age-distr.csv', 'vaccinations_example.yml', 'test_cases.csv', 'disease_covid19.yml', 'building_types_map.yml', 'klaipeda_buildings.csv']
/home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/results/klaipeda_localhost_1/RUNS/extend-lockdown-1-0.475_2 ['covid_data'] ['covid_out_deaths_0.csv', 'env.log', 'covid_out_infections_0.csv', 'covid_out_recoveries_0.csv', 'out.csv', 'offices.csv', 'simsetting.csv', 'env.yml', 'covid_out_hospitalisations_0.csv', 'klaipeda_localhost_1_extend-lockdown-1-0.475_2.sh']
file found at: /home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/results/klaipeda_localhost_1/RUNS/extend-lockdown-1-0.475_2/covid_out_infections_0.csv
/home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/results/klaipeda_localhost_1/RUNS/extend-lockdown-1-0.475_2/covid_data [] ['needs.csv', 'measures_uk.yml', 'age-distr.csv', 'vaccinations_example.yml', 'test_cases.csv', 'disease_covid19.yml', 'building_types_map.yml', 'klaipeda_buildings.csv']
/home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/results/klaipeda_localhost_1/RUNS/extend-lockdown-1-0.475_4 ['covid_data'] ['covid_out_deaths_0.csv', 'env.log', 'covid_out_infections_0.csv', 'covid_out_recoveries_0.csv', 'out.csv', 'offices.csv', 'simsetting.csv', 'klaipeda_localhost_1_extend-lockdown-1-0.475_4.sh', 'env.yml', 'covid_out_hospitalisations_0.csv']
file found at: /home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/results/klaipeda_localhost_1/RUNS/extend-lockdown-1-0.475_4/covid_out_infections_0.csv
/home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/results/klaipeda_localhost_1/RUNS/extend-lockdown-1-0.475_4/covid_data [] ['needs.csv', 'measures_uk.yml', 'age-distr.csv', 'vaccinations_example.yml', 'test_cases.csv', 'disease_covid19.yml', 'building_types_map.yml', 'klaipeda_buildings.csv']
/home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/results/klaipeda_localhost_1/RUNS/extend-lockdown-1-0.475_3 ['covid_data'] ['covid_out_deaths_0.csv', 'env.log', 'covid_out_infections_0.csv', 'covid_out_recoveries_0.csv', 'out.csv', 'offices.csv', 'simsetting.csv', 'env.yml', 'covid_out_hospitalisations_0.csv', 'klaipeda_localhost_1_extend-lockdown-1-0.475_3.sh']
file found at: /home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/results/klaipeda_localhost_1/RUNS/extend-lockdown-1-0.475_3/covid_out_infections_0.csv
/home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/results/klaipeda_localhost_1/RUNS/extend-lockdown-1-0.475_3/covid_data [] ['needs.csv', 'measures_uk.yml', 'age-distr.csv', 'vaccinations_example.yml', 'test_cases.csv', 'disease_covid19.yml', 'building_types_map.yml', 'klaipeda_buildings.csv']
/home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/results/klaipeda_localhost_1/RUNS/extend-lockdown-1-0.475_5 ['covid_data'] ['covid_out_deaths_0.csv', 'env.log', 'covid_out_infections_0.csv', 'covid_out_recoveries_0.csv', 'out.csv', 'offices.csv', 'simsetting.csv', 'env.yml', 'covid_out_hospitalisations_0.csv', 'klaipeda_localhost_1_extend-lockdown-1-0.475_5.sh']
file found at: /home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/results/klaipeda_localhost_1/RUNS/extend-lockdown-1-0.475_5/covid_out_infections_0.csv
/home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/results/klaipeda_localhost_1/RUNS/extend-lockdown-1-0.475_5/covid_data [] ['needs.csv', 'measures_uk.yml', 'age-distr.csv', 'vaccinations_example.yml', 'test_cases.csv', 'disease_covid19.yml', 'building_types_map.yml', 'klaipeda_buildings.csv']
Traceback (most recent call last):
  File "/home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/fabsim/bin/fabsim", line 46, in <module>
    sys.exit(fabsim_main.main())
  File "/home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/fabsim/base/fabsim_main.py", line 150, in main
    env.exec_func(*env.task_args, **env.task_kwargs)
  File "/home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/fabsim/base/decorators.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/fabsim/base/decorators.py", line 127, in wrapper
    return func(*args, **kwargs)
  File "/home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/plugins/FabCovid19/visualisation/PlotByLocationType.py", line 63, in facs_locationplot
    for i in range(pdf['time'].min(), pdf['time'].max()):
  File "/home/arindam/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 10827, in min
    return NDFrame.min(self, axis, skipna, level, numeric_only, **kwargs)
  File "/home/arindam/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 10350, in min
    return self._stat_function(
  File "/home/arindam/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 10345, in _stat_function
    return self._reduce(
  File "/home/arindam/.local/lib/python3.8/site-packages/pandas/core/series.py", line 4391, in _reduce
    return op(delegate, skipna=skipna, **kwds)
  File "/home/arindam/.local/lib/python3.8/site-packages/pandas/core/nanops.py", line 155, in f
    result = alt(values, axis=axis, skipna=skipna, **kwds)
  File "/home/arindam/.local/lib/python3.8/site-packages/pandas/core/nanops.py", line 410, in new_func
    result = func(values, axis=axis, skipna=skipna, mask=mask, **kwargs)
  File "/home/arindam/.local/lib/python3.8/site-packages/pandas/core/nanops.py", line 1017, in reduction
    result = getattr(values, meth)(axis)
  File "/home/arindam/.local/lib/python3.8/site-packages/numpy/core/_methods.py", line 44, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
TypeError: '<=' not supported between instances of 'int' and 'str'

**Comment by djgroen** [comment]
Hi Arindam.

This is the error that matters:

File "/home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/plugins/FabCovid19/visualisation/PlotByLocationType.py", line 63, in facs_locationplot
for i in range(pdf['time'].min(), pdf['time'].max()):

Could you perhaps paste in the first two rows out your out.csv file? It could be that some kind of mismatch emerged there.

Also just as a second check: are you doing a locationplot on runs that you did with FabSim? If not, then please make sure that your output file is named 'out.csv'.

**Comment by arindamsaha1507** [comment]
Hi Derek,

Here are the first two lines of the out.csv file.

#time,date,susceptible,exposed,infectious,recovered,dead,immune,num infections today,num hospitalisations today,hospital bed occupancy,num hospitalisations today (data),cum num hospitalisations today,cum num infections today
1,2/3/2020,337671,16374,6910,1751,2,0,5815,11,26,0.0,11,5815


Yes, I am doing the locationplots using FabSim.

**Comment by arindamsaha1507** [comment]
@djgroen Now I am facing a new error after updating to the new version. Now the simulations give a runtime error

RuntimeError: 
local() encountered an error (return code 2)while executing 'ssh -Y -p 22 arindam@localhost '/bin/true || true &&  /home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/localhost_exe/FabSim/results/klaipeda_localhost_1/RUNS/extend-lockdown-1-0.475/klaipeda_localhost_1_extend-lockdown-1-0.475.sh''

And the previous problem with locationplot continues. Perhaps it will be good if you assist with the manual debug.

**Comment by djgroen** [comment]
This was caused by a duplicate header in the infections output csv file. This has now been amended.

See 01bf638d995ff761ec8208ef7340bbb6c484f359
