### ISSUE TITLE
Change the date format in measures files to yyyy-mm-dd

### ISSUE THREAD

**Issue by arindamsaha1507** [djgroen/facs#25]

**Comment by djgroen** [comment]
Okay. I have now pushed changes to support this. Please modify the date_format variable in your measures yml to define custom formats.

To do the format you propose here, please use:
`date_format: '%Y/%m/%d'`

**Comment by djgroen** [comment]
Let me know if it works :).

**Comment by arindamsaha1507** [comment]
Works! Thanks for the improvement!
