### ISSUE TITLE
Redesign hospital/clinic selection

### ISSUE THREAD

**Issue by djgroen** [djgroen/facs#3]
Currently, persons go to the nearest medical facility when either visiting or being hospitalised. Sometimes these facilities are rather small, creating asymmetric effects.

My aim is to implement the following:
- When at home: random chance to visit medical facility irrespective of type (some will visit hospitals, some clinics).
- When hospitalised: exclude non-hospital medical facilities from selection.

Imran, what to do you think of this approach?

**Comment by imahmood786** [comment]
I agree with both points. For the first point: will it be based on nearest facility or simply the random selection?

**Comment by djgroen** [comment]
First attempt at implementation here: b524400a3b8b0f821d50e0bc5f8b4bdb9d5a0147

**Comment by djgroen** [comment]
Seems to work as intended.
