### ISSUE TITLE
Modify nearest location algorithm

### ISSUE THREAD

**Issue by djgroen** [djgroen/facs#8]
When household choose parks, shops etc., size should also play a partial role, in addition to distance.

**Comment by arindamsaha1507** [comment]
Needs updating for FACS 2.0.

**Comment by djgroen** [comment]
- Houses: N/A
- Offices
  - Neighbour list creation: nearest 50 offices, then randomly pick one. 
  - Choice in list: N/A
- Shopping
  - Neighbour list creation: nearest 10 shops 
  - Choice in list: unweighted random choice
- Park
  - Neighbour list creation: nearest park 
  - Choice in list: N/A  
- Leisure
  - Neighbour list creation: nearest 10 leisure
  - Choice in list: unweighted random choice
- School
  - Neighbour list creation: nearest 5 schools, then randomly pick one. 
  - Choice in list: N/A
- Hospital
  - Neighbour list creation: nearest 5 hospitals
  - Choice in list: weighted random by area.
- Supermarket
  - Neighbour list creation: nearest 10 supermarkets
  - Choice in list: unweighted random choice
